name: unified_checkout_sdk
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_remix: ^0.0.3
  provider: ^6.0.0
  cached_network_image: ^3.2.3
  animated_toggle_switch: ^0.7.0
  flutter_svg: ^2.0.7
  webview_flutter: ^4.2.4
  pdf: ^3.4.0
  path_provider: ^2.0.4
  flutter_html_to_pdf: ^0.7.0
  printing: ^5.11.0
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/drawable/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/nunitosans_extrabold.ttf
          weight: 700
        - asset: assets/fonts/nunitosans_regular.ttf